### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by ORCA666** [mgeeky/UnhookMe#1]
Hello @mgeeky hope ur doing good,
Well I have a simple silly question, I am using syscalls, (exactly the following : NtAllocateVirtualMemory, NtWriteVirtualMemory, NtCreateThreadEx, NtOpenProcess), I want to know if this repo (btw it's amazing) can unhook these functions if they are getting hooked, I am asking this cz it syscalls that I am using and not some normal win api calls .
So will it work in this situation ? 

Thanks for the code, & hope u reply soon :)

**Comment by mgeeky** [comment]
Hi, so this code attempts to unhook standard exported functions. Whenver you want to call any function from any library directly (that is not through a direct syscall approach) and you want to be sure it's unhooked from user-mode perspective, you can incorporate the code from this repository.

So it does nothing fancy with direct syscalls approach.

Hope that answers your question.

Regards,
M.

**Comment by ORCA666** [comment]
@mgeeky hey, thanks for the reply, I figured this couple of days ago, so I used hellsgate way to do the trick, it worked :)

Anyways, I'm sure I'll use this repo in the future.
Thanks for the share again.

Have a nice day
